### ISSUE TITLE
Failed to parse created manifest.json

### ISSUE THREAD

**Issue by Juice805** [ModifiedCommand/ConvertJavaTextureToBedrock#3]
While attempting to convert the [Ozocraft Remix](https://www.curseforge.com/minecraft/texture-packs/ozocraft-remix) texture pack [version 1.19v3](https://www.curseforge.com/minecraft/texture-packs/ozocraft-remix/files/3898548) the conversion failed:

```
Start conversion
...
Create metadata manifest.json
ERROR: SyntaxError: JSON.parse: bad control character in string literal at line 5 column 16 of the JSON data
```

[Full log here](https://pastebin.com/3K0YfST3)

**Comment by PiSaucer** [comment]
I am unable to fix this issue because it's JSON issue. After looking at the `pack.mcmeta`, I notice that the comment created a spacing issue confusing the generator. To fix this, just replace the information with:

```json
{
   "pack":{
      "pack_format": 9,
      "description":"§6OzoCraft Remix §21.19\n§eFan updated by AEON"
   }
}
```

```json
{
  "pack": {
	"pack_format": 9,
    "description": "§6OzoCraft Remix §21.19\n§eFan updated by AEON",
 "__comment": "

// These Spaces

This is a fan updated Classic 32x32 pack originally by Ozo.se // These weird line breaks that don't use /n
Fixes issues with Lanterns, Netherite etc by filling in 
missing items and parity

// These Spaces

"}
}
```

The comments show the issues with this `pack.mcmeta`
