### ISSUE TITLE
Will this ever update to 1.20?

### ISSUE THREAD

**Issue by The-Adoon2** [ModifiedCommand/ConvertJavaTextureToBedrock#4]

**Comment by PiSaucer** [comment]
Done. I mostly just remove the pack check. I don't have the time to see what changed between 1.16 and 1.20. If you have time please check it out at [ModifiedCommand/ConvertJavaTextureToBedrockApi](https://github.com/ModifiedCommand/ConvertJavaTextureToBedrockApi/).
