### ISSUE TITLE
ERROR: TypeError: this.data is undefined

### ISSUE THREAD

**Issue by Puyodead1** [ModifiedCommand/ConvertJavaTextureToBedrock#6]
**Describe the issue**
Trying to convert packs results in `ERROR: TypeError: this.data is undefined`

**System info**

***Converting***
System OS: Windows 10
Browser: Firefox (also tried on chrome)

***Game***
System OS: Windows 10

**Texture pack**
Link to download: 
https://modrinth.com/resourcepack/3d-default
https://modrinth.com/resourcepack/rays-3d-rails
https://modrinth.com/resourcepack/rays-3d-ladders
tried with many others

**Comment by PiSaucer** [comment]
This doesn't convert optifine packs. Those packs have code that will not work bedrock, so it creates the error.
