### ISSUE TITLE
ERROR: Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by Some0neXD** [ModifiedCommand/ConvertJavaTextureToBedrock#7]
the 
ERROR: Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator)) 
desnt work
![image](https://github.com/ModifiedCommand/ConvertJavaTextureToBedrock/assets/148023838/a27c1ef9-aa28-404c-b984-8e5123a840c4)

**Comment by Some0neXD** [comment]
help

**Comment by Kamillaova** [comment]
@ModifiedCommand

**Comment by Kamillaova** [comment]
@PiSaucer

**Comment by PiSaucer** [comment]
Send a link to the texture pack that you were trying to convert.

**Comment by Kamillaova** [comment]
> Send a link to the texture pack that you were trying to convert.

https://files.catbox.moe/pk4b5d.zip

**Comment by PiSaucer** [comment]
Fixed by [Teelair's](https://github.com/Teelair) Fix the [Add missing comma #2](https://github.com/ModifiedCommand/ConvertJavaTextureToBedrockApi/pull/2)
