### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Some0neXD** [ModifiedCommand/ConvertJavaTextureToBedrock#8]
![image](https://github.com/ModifiedCommand/ConvertJavaTextureToBedrock/assets/148023838/21c46e63-69f8-4285-b151-d35677a2f754)
here is the texturepack
[!         Â§9Â§lAsÂ§5Â§ltro Â§8Â§l[Â§fÂ§816xÂ§l] (2).zip](https://github.com/ModifiedCommand/ConvertJavaTextureToBedrock/files/15316325/A.9A.lAsA.5A.ltro.A.8A.l.A.fA.816xA.l.2.zip)

**Comment by PiSaucer** [comment]
You need to change the `pack.mcmeta` since it has newline character in the description (Line 4, Col 74) in it. This doesn't follow json format, this is a creator issue. If you make the following changes it should work.

```json
{
  "pack": {
    "pack_format": 7,
    "description": "        §9§lby §5§lidyll §f§l- §9§lDefault §5§lNebula
    "
  }
}
```

```json
{
  "pack": {
    "pack_format": 7,
    "description": "        §9§lby §5§lidyll §f§l- §9§lDefault §5§lNebula"
  }
}
```
